# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/cmake-3.16.3-Linux-x86_64/bin/cmake

# The command to remove a file.
RM = /opt/cmake-3.16.3-Linux-x86_64/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/leo/workspace/ruian_2wire/common/app/common

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/leo/workspace/ruian_2wire/common/app/common

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/cmake-3.16.3-Linux-x86_64/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/cmake-3.16.3-Linux-x86_64/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/leo/workspace/ruian_2wire/common/app/common/CMakeFiles /home/leo/workspace/ruian_2wire/common/app/common/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/leo/workspace/ruian_2wire/common/app/common/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ../ANYKA37E.BIN

# Build rule for target.
../ANYKA37E.BIN: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ../ANYKA37E.BIN
.PHONY : ../ANYKA37E.BIN

# fast build rule for target.
../ANYKA37E.BIN/fast:
	$(MAKE) -f src/CMakeFiles/../ANYKA37E.BIN.dir/build.make src/CMakeFiles/../ANYKA37E.BIN.dir/build
.PHONY : ../ANYKA37E.BIN/fast

#=============================================================================
# Target rules for targets named lvgl_lib

# Build rule for target.
lvgl_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lvgl_lib
.PHONY : lvgl_lib

# fast build rule for target.
lvgl_lib/fast:
	$(MAKE) -f src/lvgl/CMakeFiles/lvgl_lib.dir/build.make src/lvgl/CMakeFiles/lvgl_lib.dir/build
.PHONY : lvgl_lib/fast

#=============================================================================
# Target rules for targets named lv_drivers_lib

# Build rule for target.
lv_drivers_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lv_drivers_lib
.PHONY : lv_drivers_lib

# fast build rule for target.
lv_drivers_lib/fast:
	$(MAKE) -f src/lv_drivers/CMakeFiles/lv_drivers_lib.dir/build.make src/lv_drivers/CMakeFiles/lv_drivers_lib.dir/build
.PHONY : lv_drivers_lib/fast

#=============================================================================
# Target rules for targets named lv_qrcode_lib

# Build rule for target.
lv_qrcode_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lv_qrcode_lib
.PHONY : lv_qrcode_lib

# fast build rule for target.
lv_qrcode_lib/fast:
	$(MAKE) -f src/lv_qrcode/CMakeFiles/lv_qrcode_lib.dir/build.make src/lv_qrcode/CMakeFiles/lv_qrcode_lib.dir/build
.PHONY : lv_qrcode_lib/fast

#=============================================================================
# Target rules for targets named leo_api_lib

# Build rule for target.
leo_api_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 leo_api_lib
.PHONY : leo_api_lib

# fast build rule for target.
leo_api_lib/fast:
	$(MAKE) -f src/api/CMakeFiles/leo_api_lib.dir/build.make src/api/CMakeFiles/leo_api_lib.dir/build
.PHONY : leo_api_lib/fast

#=============================================================================
# Target rules for targets named samplerate

# Build rule for target.
samplerate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 samplerate
.PHONY : samplerate

# fast build rule for target.
samplerate/fast:
	$(MAKE) -f src/api/samplerate/CMakeFiles/samplerate.dir/build.make src/api/samplerate/CMakeFiles/samplerate.dir/build
.PHONY : samplerate/fast

#=============================================================================
# Target rules for targets named xls

# Build rule for target.
xls: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xls
.PHONY : xls

# fast build rule for target.
xls/fast:
	$(MAKE) -f src/tuya_batch_production_sdk/xls/CMakeFiles/xls.dir/build.make src/tuya_batch_production_sdk/xls/CMakeFiles/xls.dir/build
.PHONY : xls/fast

#=============================================================================
# Target rules for targets named iniparser

# Build rule for target.
iniparser: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 iniparser
.PHONY : iniparser

# fast build rule for target.
iniparser/fast:
	$(MAKE) -f src/iniparser/CMakeFiles/iniparser.dir/build.make src/iniparser/CMakeFiles/iniparser.dir/build
.PHONY : iniparser/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... ../ANYKA37E.BIN"
	@echo "... lvgl_lib"
	@echo "... lv_drivers_lib"
	@echo "... lv_qrcode_lib"
	@echo "... leo_api_lib"
	@echo "... samplerate"
	@echo "... xls"
	@echo "... iniparser"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

