# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/cmake-3.16.3-Linux-x86_64/bin/cmake

# The command to remove a file.
RM = /opt/cmake-3.16.3-Linux-x86_64/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/leo/workspace/ruian_2wire/common/app/common

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/leo/workspace/ruian_2wire/common/app/common

# Include any dependencies generated for this target.
include src/CMakeFiles/../ANYKA37E.BIN.dir/depend.make

# Include the progress variables for this target.
include src/CMakeFiles/../ANYKA37E.BIN.dir/progress.make

# Include the compile flags for this target's objects.
include src/CMakeFiles/../ANYKA37E.BIN.dir/flags.make

src/CMakeFiles/../ANYKA37E.BIN.dir/main.c.o: src/CMakeFiles/../ANYKA37E.BIN.dir/flags.make
src/CMakeFiles/../ANYKA37E.BIN.dir/main.c.o: src/main.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/leo/workspace/ruian_2wire/common/app/common/CMakeFiles --progress-num=$(CMAKE_PROGRESS_1) "Building C object src/CMakeFiles/../ANYKA37E.BIN.dir/main.c.o"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/../ANYKA37E.BIN.dir/main.c.o   -c /home/leo/workspace/ruian_2wire/common/app/common/src/main.c

src/CMakeFiles/../ANYKA37E.BIN.dir/main.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../ANYKA37E.BIN.dir/main.c.i"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/leo/workspace/ruian_2wire/common/app/common/src/main.c > CMakeFiles/../ANYKA37E.BIN.dir/main.c.i

src/CMakeFiles/../ANYKA37E.BIN.dir/main.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../ANYKA37E.BIN.dir/main.c.s"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/leo/workspace/ruian_2wire/common/app/common/src/main.c -o CMakeFiles/../ANYKA37E.BIN.dir/main.c.s

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/language.c.o: src/CMakeFiles/../ANYKA37E.BIN.dir/flags.make
src/CMakeFiles/../ANYKA37E.BIN.dir/layout/language.c.o: src/layout/language.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/leo/workspace/ruian_2wire/common/app/common/CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Building C object src/CMakeFiles/../ANYKA37E.BIN.dir/layout/language.c.o"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/../ANYKA37E.BIN.dir/layout/language.c.o   -c /home/leo/workspace/ruian_2wire/common/app/common/src/layout/language.c

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/language.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../ANYKA37E.BIN.dir/layout/language.c.i"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/leo/workspace/ruian_2wire/common/app/common/src/layout/language.c > CMakeFiles/../ANYKA37E.BIN.dir/layout/language.c.i

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/language.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../ANYKA37E.BIN.dir/layout/language.c.s"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/leo/workspace/ruian_2wire/common/app/common/src/layout/language.c -o CMakeFiles/../ANYKA37E.BIN.dir/layout/language.c.s

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_add_wifi.c.o: src/CMakeFiles/../ANYKA37E.BIN.dir/flags.make
src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_add_wifi.c.o: src/layout/layout_add_wifi.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/leo/workspace/ruian_2wire/common/app/common/CMakeFiles --progress-num=$(CMAKE_PROGRESS_3) "Building C object src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_add_wifi.c.o"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_add_wifi.c.o   -c /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_add_wifi.c

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_add_wifi.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_add_wifi.c.i"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_add_wifi.c > CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_add_wifi.c.i

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_add_wifi.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_add_wifi.c.s"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_add_wifi.c -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_add_wifi.c.s

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_background.c.o: src/CMakeFiles/../ANYKA37E.BIN.dir/flags.make
src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_background.c.o: src/layout/layout_background.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/leo/workspace/ruian_2wire/common/app/common/CMakeFiles --progress-num=$(CMAKE_PROGRESS_4) "Building C object src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_background.c.o"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_background.c.o   -c /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_background.c

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_background.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_background.c.i"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_background.c > CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_background.c.i

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_background.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_background.c.s"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_background.c -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_background.c.s

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_cctv.c.o: src/CMakeFiles/../ANYKA37E.BIN.dir/flags.make
src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_cctv.c.o: src/layout/layout_cctv.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/leo/workspace/ruian_2wire/common/app/common/CMakeFiles --progress-num=$(CMAKE_PROGRESS_5) "Building C object src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_cctv.c.o"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_cctv.c.o   -c /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_cctv.c

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_cctv.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_cctv.c.i"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_cctv.c > CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_cctv.c.i

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_cctv.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_cctv.c.s"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_cctv.c -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_cctv.c.s

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_close.c.o: src/CMakeFiles/../ANYKA37E.BIN.dir/flags.make
src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_close.c.o: src/layout/layout_close.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/leo/workspace/ruian_2wire/common/app/common/CMakeFiles --progress-num=$(CMAKE_PROGRESS_6) "Building C object src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_close.c.o"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_close.c.o   -c /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_close.c

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_close.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_close.c.i"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_close.c > CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_close.c.i

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_close.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_close.c.s"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_close.c -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_close.c.s

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_common.c.o: src/CMakeFiles/../ANYKA37E.BIN.dir/flags.make
src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_common.c.o: src/layout/layout_common.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/leo/workspace/ruian_2wire/common/app/common/CMakeFiles --progress-num=$(CMAKE_PROGRESS_7) "Building C object src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_common.c.o"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_common.c.o   -c /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_common.c

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_common.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_common.c.i"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_common.c > CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_common.c.i

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_common.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_common.c.s"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_common.c -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_common.c.s

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_connect_wifi.c.o: src/CMakeFiles/../ANYKA37E.BIN.dir/flags.make
src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_connect_wifi.c.o: src/layout/layout_connect_wifi.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/leo/workspace/ruian_2wire/common/app/common/CMakeFiles --progress-num=$(CMAKE_PROGRESS_8) "Building C object src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_connect_wifi.c.o"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_connect_wifi.c.o   -c /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_connect_wifi.c

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_connect_wifi.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_connect_wifi.c.i"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_connect_wifi.c > CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_connect_wifi.c.i

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_connect_wifi.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_connect_wifi.c.s"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_connect_wifi.c -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_connect_wifi.c.s

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_customize_ring.c.o: src/CMakeFiles/../ANYKA37E.BIN.dir/flags.make
src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_customize_ring.c.o: src/layout/layout_customize_ring.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/leo/workspace/ruian_2wire/common/app/common/CMakeFiles --progress-num=$(CMAKE_PROGRESS_9) "Building C object src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_customize_ring.c.o"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_customize_ring.c.o   -c /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_customize_ring.c

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_customize_ring.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_customize_ring.c.i"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_customize_ring.c > CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_customize_ring.c.i

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_customize_ring.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_customize_ring.c.s"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_customize_ring.c -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_customize_ring.c.s

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_define.c.o: src/CMakeFiles/../ANYKA37E.BIN.dir/flags.make
src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_define.c.o: src/layout/layout_define.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/leo/workspace/ruian_2wire/common/app/common/CMakeFiles --progress-num=$(CMAKE_PROGRESS_10) "Building C object src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_define.c.o"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_define.c.o   -c /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_define.c

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_define.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_define.c.i"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_define.c > CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_define.c.i

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_define.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_define.c.s"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_define.c -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_define.c.s

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_device_setting.c.o: src/CMakeFiles/../ANYKA37E.BIN.dir/flags.make
src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_device_setting.c.o: src/layout/layout_device_setting.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/leo/workspace/ruian_2wire/common/app/common/CMakeFiles --progress-num=$(CMAKE_PROGRESS_11) "Building C object src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_device_setting.c.o"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_device_setting.c.o   -c /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_device_setting.c

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_device_setting.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_device_setting.c.i"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_device_setting.c > CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_device_setting.c.i

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_device_setting.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_device_setting.c.s"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_device_setting.c -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_device_setting.c.s

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_home.c.o: src/CMakeFiles/../ANYKA37E.BIN.dir/flags.make
src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_home.c.o: src/layout/layout_home.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/leo/workspace/ruian_2wire/common/app/common/CMakeFiles --progress-num=$(CMAKE_PROGRESS_12) "Building C object src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_home.c.o"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_home.c.o   -c /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_home.c

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_home.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_home.c.i"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_home.c > CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_home.c.i

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_home.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_home.c.s"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_home.c -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_home.c.s

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_interphone.c.o: src/CMakeFiles/../ANYKA37E.BIN.dir/flags.make
src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_interphone.c.o: src/layout/layout_interphone.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/leo/workspace/ruian_2wire/common/app/common/CMakeFiles --progress-num=$(CMAKE_PROGRESS_13) "Building C object src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_interphone.c.o"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_interphone.c.o   -c /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_interphone.c

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_interphone.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_interphone.c.i"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_interphone.c > CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_interphone.c.i

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_interphone.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_interphone.c.s"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_interphone.c -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_interphone.c.s

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_keyboard.c.o: src/CMakeFiles/../ANYKA37E.BIN.dir/flags.make
src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_keyboard.c.o: src/layout/layout_keyboard.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/leo/workspace/ruian_2wire/common/app/common/CMakeFiles --progress-num=$(CMAKE_PROGRESS_14) "Building C object src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_keyboard.c.o"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_keyboard.c.o   -c /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_keyboard.c

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_keyboard.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_keyboard.c.i"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_keyboard.c > CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_keyboard.c.i

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_keyboard.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_keyboard.c.s"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_keyboard.c -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_keyboard.c.s

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_logo.c.o: src/CMakeFiles/../ANYKA37E.BIN.dir/flags.make
src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_logo.c.o: src/layout/layout_logo.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/leo/workspace/ruian_2wire/common/app/common/CMakeFiles --progress-num=$(CMAKE_PROGRESS_15) "Building C object src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_logo.c.o"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_logo.c.o   -c /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_logo.c

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_logo.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_logo.c.i"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_logo.c > CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_logo.c.i

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_logo.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_logo.c.s"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_logo.c -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_logo.c.s

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_monitor.c.o: src/CMakeFiles/../ANYKA37E.BIN.dir/flags.make
src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_monitor.c.o: src/layout/layout_monitor.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/leo/workspace/ruian_2wire/common/app/common/CMakeFiles --progress-num=$(CMAKE_PROGRESS_16) "Building C object src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_monitor.c.o"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_monitor.c.o   -c /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_monitor.c

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_monitor.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_monitor.c.i"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_monitor.c > CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_monitor.c.i

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_monitor.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_monitor.c.s"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_monitor.c -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_monitor.c.s

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_motion.c.o: src/CMakeFiles/../ANYKA37E.BIN.dir/flags.make
src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_motion.c.o: src/layout/layout_motion.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/leo/workspace/ruian_2wire/common/app/common/CMakeFiles --progress-num=$(CMAKE_PROGRESS_17) "Building C object src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_motion.c.o"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_motion.c.o   -c /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_motion.c

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_motion.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_motion.c.i"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_motion.c > CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_motion.c.i

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_motion.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_motion.c.s"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_motion.c -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_motion.c.s

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_photo.c.o: src/CMakeFiles/../ANYKA37E.BIN.dir/flags.make
src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_photo.c.o: src/layout/layout_photo.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/leo/workspace/ruian_2wire/common/app/common/CMakeFiles --progress-num=$(CMAKE_PROGRESS_18) "Building C object src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_photo.c.o"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_photo.c.o   -c /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_photo.c

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_photo.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_photo.c.i"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_photo.c > CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_photo.c.i

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_photo.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_photo.c.s"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_photo.c -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_photo.c.s

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_playback.c.o: src/CMakeFiles/../ANYKA37E.BIN.dir/flags.make
src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_playback.c.o: src/layout/layout_playback.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/leo/workspace/ruian_2wire/common/app/common/CMakeFiles --progress-num=$(CMAKE_PROGRESS_19) "Building C object src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_playback.c.o"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_playback.c.o   -c /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_playback.c

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_playback.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_playback.c.i"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_playback.c > CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_playback.c.i

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_playback.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_playback.c.s"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_playback.c -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_playback.c.s

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_product_introduction.c.o: src/CMakeFiles/../ANYKA37E.BIN.dir/flags.make
src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_product_introduction.c.o: src/layout/layout_product_introduction.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/leo/workspace/ruian_2wire/common/app/common/CMakeFiles --progress-num=$(CMAKE_PROGRESS_20) "Building C object src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_product_introduction.c.o"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_product_introduction.c.o   -c /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_product_introduction.c

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_product_introduction.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_product_introduction.c.i"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_product_introduction.c > CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_product_introduction.c.i

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_product_introduction.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_product_introduction.c.s"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_product_introduction.c -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_product_introduction.c.s

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_ring.c.o: src/CMakeFiles/../ANYKA37E.BIN.dir/flags.make
src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_ring.c.o: src/layout/layout_ring.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/leo/workspace/ruian_2wire/common/app/common/CMakeFiles --progress-num=$(CMAKE_PROGRESS_21) "Building C object src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_ring.c.o"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_ring.c.o   -c /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_ring.c

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_ring.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_ring.c.i"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_ring.c > CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_ring.c.i

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_ring.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_ring.c.s"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_ring.c -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_ring.c.s

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_set_floor_number.c.o: src/CMakeFiles/../ANYKA37E.BIN.dir/flags.make
src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_set_floor_number.c.o: src/layout/layout_set_floor_number.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/leo/workspace/ruian_2wire/common/app/common/CMakeFiles --progress-num=$(CMAKE_PROGRESS_22) "Building C object src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_set_floor_number.c.o"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_set_floor_number.c.o   -c /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_set_floor_number.c

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_set_floor_number.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_set_floor_number.c.i"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_set_floor_number.c > CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_set_floor_number.c.i

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_set_floor_number.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_set_floor_number.c.s"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_set_floor_number.c -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_set_floor_number.c.s

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_set_language.c.o: src/CMakeFiles/../ANYKA37E.BIN.dir/flags.make
src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_set_language.c.o: src/layout/layout_set_language.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/leo/workspace/ruian_2wire/common/app/common/CMakeFiles --progress-num=$(CMAKE_PROGRESS_23) "Building C object src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_set_language.c.o"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_set_language.c.o   -c /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_set_language.c

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_set_language.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_set_language.c.i"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_set_language.c > CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_set_language.c.i

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_set_language.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_set_language.c.s"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_set_language.c -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_set_language.c.s

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_set_wifi.c.o: src/CMakeFiles/../ANYKA37E.BIN.dir/flags.make
src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_set_wifi.c.o: src/layout/layout_set_wifi.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/leo/workspace/ruian_2wire/common/app/common/CMakeFiles --progress-num=$(CMAKE_PROGRESS_24) "Building C object src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_set_wifi.c.o"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_set_wifi.c.o   -c /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_set_wifi.c

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_set_wifi.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_set_wifi.c.i"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_set_wifi.c > CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_set_wifi.c.i

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_set_wifi.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_set_wifi.c.s"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_set_wifi.c -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_set_wifi.c.s

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting.c.o: src/CMakeFiles/../ANYKA37E.BIN.dir/flags.make
src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting.c.o: src/layout/layout_setting.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/leo/workspace/ruian_2wire/common/app/common/CMakeFiles --progress-num=$(CMAKE_PROGRESS_25) "Building C object src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting.c.o"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting.c.o   -c /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_setting.c

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting.c.i"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_setting.c > CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting.c.i

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting.c.s"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_setting.c -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting.c.s

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_cctv.c.o: src/CMakeFiles/../ANYKA37E.BIN.dir/flags.make
src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_cctv.c.o: src/layout/layout_setting_cctv.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/leo/workspace/ruian_2wire/common/app/common/CMakeFiles --progress-num=$(CMAKE_PROGRESS_26) "Building C object src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_cctv.c.o"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_cctv.c.o   -c /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_setting_cctv.c

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_cctv.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_cctv.c.i"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_setting_cctv.c > CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_cctv.c.i

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_cctv.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_cctv.c.s"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_setting_cctv.c -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_cctv.c.s

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_cctv_add.c.o: src/CMakeFiles/../ANYKA37E.BIN.dir/flags.make
src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_cctv_add.c.o: src/layout/layout_setting_cctv_add.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/leo/workspace/ruian_2wire/common/app/common/CMakeFiles --progress-num=$(CMAKE_PROGRESS_27) "Building C object src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_cctv_add.c.o"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_cctv_add.c.o   -c /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_setting_cctv_add.c

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_cctv_add.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_cctv_add.c.i"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_setting_cctv_add.c > CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_cctv_add.c.i

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_cctv_add.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_cctv_add.c.s"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_setting_cctv_add.c -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_cctv_add.c.s

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_cctv_brand.c.o: src/CMakeFiles/../ANYKA37E.BIN.dir/flags.make
src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_cctv_brand.c.o: src/layout/layout_setting_cctv_brand.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/leo/workspace/ruian_2wire/common/app/common/CMakeFiles --progress-num=$(CMAKE_PROGRESS_28) "Building C object src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_cctv_brand.c.o"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_cctv_brand.c.o   -c /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_setting_cctv_brand.c

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_cctv_brand.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_cctv_brand.c.i"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_setting_cctv_brand.c > CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_cctv_brand.c.i

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_cctv_brand.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_cctv_brand.c.s"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_setting_cctv_brand.c -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_cctv_brand.c.s

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_cctv_information.c.o: src/CMakeFiles/../ANYKA37E.BIN.dir/flags.make
src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_cctv_information.c.o: src/layout/layout_setting_cctv_information.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/leo/workspace/ruian_2wire/common/app/common/CMakeFiles --progress-num=$(CMAKE_PROGRESS_29) "Building C object src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_cctv_information.c.o"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_cctv_information.c.o   -c /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_setting_cctv_information.c

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_cctv_information.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_cctv_information.c.i"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_setting_cctv_information.c > CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_cctv_information.c.i

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_cctv_information.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_cctv_information.c.s"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_setting_cctv_information.c -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_cctv_information.c.s

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_cctv_write.c.o: src/CMakeFiles/../ANYKA37E.BIN.dir/flags.make
src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_cctv_write.c.o: src/layout/layout_setting_cctv_write.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/leo/workspace/ruian_2wire/common/app/common/CMakeFiles --progress-num=$(CMAKE_PROGRESS_30) "Building C object src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_cctv_write.c.o"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_cctv_write.c.o   -c /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_setting_cctv_write.c

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_cctv_write.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_cctv_write.c.i"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_setting_cctv_write.c > CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_cctv_write.c.i

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_cctv_write.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_cctv_write.c.s"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_setting_cctv_write.c -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_cctv_write.c.s

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_common.c.o: src/CMakeFiles/../ANYKA37E.BIN.dir/flags.make
src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_common.c.o: src/layout/layout_setting_common.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/leo/workspace/ruian_2wire/common/app/common/CMakeFiles --progress-num=$(CMAKE_PROGRESS_31) "Building C object src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_common.c.o"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_common.c.o   -c /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_setting_common.c

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_common.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_common.c.i"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_setting_common.c > CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_common.c.i

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_common.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_common.c.s"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_setting_common.c -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_common.c.s

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_password.c.o: src/CMakeFiles/../ANYKA37E.BIN.dir/flags.make
src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_password.c.o: src/layout/layout_setting_password.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/leo/workspace/ruian_2wire/common/app/common/CMakeFiles --progress-num=$(CMAKE_PROGRESS_32) "Building C object src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_password.c.o"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_password.c.o   -c /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_setting_password.c

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_password.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_password.c.i"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_setting_password.c > CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_password.c.i

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_password.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_password.c.s"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_setting_password.c -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_password.c.s

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_room_no.c.o: src/CMakeFiles/../ANYKA37E.BIN.dir/flags.make
src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_room_no.c.o: src/layout/layout_setting_room_no.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/leo/workspace/ruian_2wire/common/app/common/CMakeFiles --progress-num=$(CMAKE_PROGRESS_33) "Building C object src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_room_no.c.o"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_room_no.c.o   -c /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_setting_room_no.c

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_room_no.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_room_no.c.i"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_setting_room_no.c > CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_room_no.c.i

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_room_no.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_room_no.c.s"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_setting_room_no.c -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_room_no.c.s

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_standby.c.o: src/CMakeFiles/../ANYKA37E.BIN.dir/flags.make
src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_standby.c.o: src/layout/layout_standby.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/leo/workspace/ruian_2wire/common/app/common/CMakeFiles --progress-num=$(CMAKE_PROGRESS_34) "Building C object src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_standby.c.o"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_standby.c.o   -c /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_standby.c

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_standby.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_standby.c.i"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_standby.c > CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_standby.c.i

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_standby.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_standby.c.s"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_standby.c -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_standby.c.s

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_system.c.o: src/CMakeFiles/../ANYKA37E.BIN.dir/flags.make
src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_system.c.o: src/layout/layout_system.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/leo/workspace/ruian_2wire/common/app/common/CMakeFiles --progress-num=$(CMAKE_PROGRESS_35) "Building C object src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_system.c.o"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_system.c.o   -c /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_system.c

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_system.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_system.c.i"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_system.c > CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_system.c.i

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_system.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_system.c.s"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_system.c -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_system.c.s

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_tuya_register.c.o: src/CMakeFiles/../ANYKA37E.BIN.dir/flags.make
src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_tuya_register.c.o: src/layout/layout_tuya_register.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/leo/workspace/ruian_2wire/common/app/common/CMakeFiles --progress-num=$(CMAKE_PROGRESS_36) "Building C object src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_tuya_register.c.o"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_tuya_register.c.o   -c /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_tuya_register.c

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_tuya_register.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_tuya_register.c.i"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_tuya_register.c > CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_tuya_register.c.i

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_tuya_register.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_tuya_register.c.s"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_tuya_register.c -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_tuya_register.c.s

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_video.c.o: src/CMakeFiles/../ANYKA37E.BIN.dir/flags.make
src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_video.c.o: src/layout/layout_video.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/leo/workspace/ruian_2wire/common/app/common/CMakeFiles --progress-num=$(CMAKE_PROGRESS_37) "Building C object src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_video.c.o"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_video.c.o   -c /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_video.c

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_video.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_video.c.i"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_video.c > CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_video.c.i

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_video.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_video.c.s"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_video.c -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_video.c.s

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_watch_dog.c.o: src/CMakeFiles/../ANYKA37E.BIN.dir/flags.make
src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_watch_dog.c.o: src/layout/layout_watch_dog.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/leo/workspace/ruian_2wire/common/app/common/CMakeFiles --progress-num=$(CMAKE_PROGRESS_38) "Building C object src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_watch_dog.c.o"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_watch_dog.c.o   -c /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_watch_dog.c

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_watch_dog.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_watch_dog.c.i"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_watch_dog.c > CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_watch_dog.c.i

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_watch_dog.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_watch_dog.c.s"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/leo/workspace/ruian_2wire/common/app/common/src/layout/layout_watch_dog.c -o CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_watch_dog.c.s

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/upgrade.c.o: src/CMakeFiles/../ANYKA37E.BIN.dir/flags.make
src/CMakeFiles/../ANYKA37E.BIN.dir/layout/upgrade.c.o: src/layout/upgrade.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/leo/workspace/ruian_2wire/common/app/common/CMakeFiles --progress-num=$(CMAKE_PROGRESS_39) "Building C object src/CMakeFiles/../ANYKA37E.BIN.dir/layout/upgrade.c.o"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/../ANYKA37E.BIN.dir/layout/upgrade.c.o   -c /home/leo/workspace/ruian_2wire/common/app/common/src/layout/upgrade.c

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/upgrade.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../ANYKA37E.BIN.dir/layout/upgrade.c.i"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/leo/workspace/ruian_2wire/common/app/common/src/layout/upgrade.c > CMakeFiles/../ANYKA37E.BIN.dir/layout/upgrade.c.i

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/upgrade.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../ANYKA37E.BIN.dir/layout/upgrade.c.s"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/leo/workspace/ruian_2wire/common/app/common/src/layout/upgrade.c -o CMakeFiles/../ANYKA37E.BIN.dir/layout/upgrade.c.s

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/user_data.c.o: src/CMakeFiles/../ANYKA37E.BIN.dir/flags.make
src/CMakeFiles/../ANYKA37E.BIN.dir/layout/user_data.c.o: src/layout/user_data.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/leo/workspace/ruian_2wire/common/app/common/CMakeFiles --progress-num=$(CMAKE_PROGRESS_40) "Building C object src/CMakeFiles/../ANYKA37E.BIN.dir/layout/user_data.c.o"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/../ANYKA37E.BIN.dir/layout/user_data.c.o   -c /home/leo/workspace/ruian_2wire/common/app/common/src/layout/user_data.c

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/user_data.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../ANYKA37E.BIN.dir/layout/user_data.c.i"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/leo/workspace/ruian_2wire/common/app/common/src/layout/user_data.c > CMakeFiles/../ANYKA37E.BIN.dir/layout/user_data.c.i

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/user_data.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../ANYKA37E.BIN.dir/layout/user_data.c.s"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/leo/workspace/ruian_2wire/common/app/common/src/layout/user_data.c -o CMakeFiles/../ANYKA37E.BIN.dir/layout/user_data.c.s

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/user_time.c.o: src/CMakeFiles/../ANYKA37E.BIN.dir/flags.make
src/CMakeFiles/../ANYKA37E.BIN.dir/layout/user_time.c.o: src/layout/user_time.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/leo/workspace/ruian_2wire/common/app/common/CMakeFiles --progress-num=$(CMAKE_PROGRESS_41) "Building C object src/CMakeFiles/../ANYKA37E.BIN.dir/layout/user_time.c.o"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/../ANYKA37E.BIN.dir/layout/user_time.c.o   -c /home/leo/workspace/ruian_2wire/common/app/common/src/layout/user_time.c

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/user_time.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../ANYKA37E.BIN.dir/layout/user_time.c.i"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/leo/workspace/ruian_2wire/common/app/common/src/layout/user_time.c > CMakeFiles/../ANYKA37E.BIN.dir/layout/user_time.c.i

src/CMakeFiles/../ANYKA37E.BIN.dir/layout/user_time.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../ANYKA37E.BIN.dir/layout/user_time.c.s"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && /opt/arm-anykav500-linux-uclibcgnueabi/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/leo/workspace/ruian_2wire/common/app/common/src/layout/user_time.c -o CMakeFiles/../ANYKA37E.BIN.dir/layout/user_time.c.s

# Object files for target ../ANYKA37E.BIN
__/ANYKA37E_BIN_OBJECTS = \
"CMakeFiles/../ANYKA37E.BIN.dir/main.c.o" \
"CMakeFiles/../ANYKA37E.BIN.dir/layout/language.c.o" \
"CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_add_wifi.c.o" \
"CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_background.c.o" \
"CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_cctv.c.o" \
"CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_close.c.o" \
"CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_common.c.o" \
"CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_connect_wifi.c.o" \
"CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_customize_ring.c.o" \
"CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_define.c.o" \
"CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_device_setting.c.o" \
"CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_home.c.o" \
"CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_interphone.c.o" \
"CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_keyboard.c.o" \
"CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_logo.c.o" \
"CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_monitor.c.o" \
"CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_motion.c.o" \
"CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_photo.c.o" \
"CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_playback.c.o" \
"CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_product_introduction.c.o" \
"CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_ring.c.o" \
"CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_set_floor_number.c.o" \
"CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_set_language.c.o" \
"CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_set_wifi.c.o" \
"CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting.c.o" \
"CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_cctv.c.o" \
"CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_cctv_add.c.o" \
"CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_cctv_brand.c.o" \
"CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_cctv_information.c.o" \
"CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_cctv_write.c.o" \
"CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_common.c.o" \
"CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_password.c.o" \
"CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_room_no.c.o" \
"CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_standby.c.o" \
"CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_system.c.o" \
"CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_tuya_register.c.o" \
"CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_video.c.o" \
"CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_watch_dog.c.o" \
"CMakeFiles/../ANYKA37E.BIN.dir/layout/upgrade.c.o" \
"CMakeFiles/../ANYKA37E.BIN.dir/layout/user_data.c.o" \
"CMakeFiles/../ANYKA37E.BIN.dir/layout/user_time.c.o"

# External object files for target ../ANYKA37E.BIN
__/ANYKA37E_BIN_EXTERNAL_OBJECTS =

src/../ANYKA37E.BIN: src/CMakeFiles/../ANYKA37E.BIN.dir/main.c.o
src/../ANYKA37E.BIN: src/CMakeFiles/../ANYKA37E.BIN.dir/layout/language.c.o
src/../ANYKA37E.BIN: src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_add_wifi.c.o
src/../ANYKA37E.BIN: src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_background.c.o
src/../ANYKA37E.BIN: src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_cctv.c.o
src/../ANYKA37E.BIN: src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_close.c.o
src/../ANYKA37E.BIN: src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_common.c.o
src/../ANYKA37E.BIN: src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_connect_wifi.c.o
src/../ANYKA37E.BIN: src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_customize_ring.c.o
src/../ANYKA37E.BIN: src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_define.c.o
src/../ANYKA37E.BIN: src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_device_setting.c.o
src/../ANYKA37E.BIN: src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_home.c.o
src/../ANYKA37E.BIN: src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_interphone.c.o
src/../ANYKA37E.BIN: src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_keyboard.c.o
src/../ANYKA37E.BIN: src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_logo.c.o
src/../ANYKA37E.BIN: src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_monitor.c.o
src/../ANYKA37E.BIN: src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_motion.c.o
src/../ANYKA37E.BIN: src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_photo.c.o
src/../ANYKA37E.BIN: src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_playback.c.o
src/../ANYKA37E.BIN: src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_product_introduction.c.o
src/../ANYKA37E.BIN: src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_ring.c.o
src/../ANYKA37E.BIN: src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_set_floor_number.c.o
src/../ANYKA37E.BIN: src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_set_language.c.o
src/../ANYKA37E.BIN: src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_set_wifi.c.o
src/../ANYKA37E.BIN: src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting.c.o
src/../ANYKA37E.BIN: src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_cctv.c.o
src/../ANYKA37E.BIN: src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_cctv_add.c.o
src/../ANYKA37E.BIN: src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_cctv_brand.c.o
src/../ANYKA37E.BIN: src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_cctv_information.c.o
src/../ANYKA37E.BIN: src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_cctv_write.c.o
src/../ANYKA37E.BIN: src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_common.c.o
src/../ANYKA37E.BIN: src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_password.c.o
src/../ANYKA37E.BIN: src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_setting_room_no.c.o
src/../ANYKA37E.BIN: src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_standby.c.o
src/../ANYKA37E.BIN: src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_system.c.o
src/../ANYKA37E.BIN: src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_tuya_register.c.o
src/../ANYKA37E.BIN: src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_video.c.o
src/../ANYKA37E.BIN: src/CMakeFiles/../ANYKA37E.BIN.dir/layout/layout_watch_dog.c.o
src/../ANYKA37E.BIN: src/CMakeFiles/../ANYKA37E.BIN.dir/layout/upgrade.c.o
src/../ANYKA37E.BIN: src/CMakeFiles/../ANYKA37E.BIN.dir/layout/user_data.c.o
src/../ANYKA37E.BIN: src/CMakeFiles/../ANYKA37E.BIN.dir/layout/user_time.c.o
src/../ANYKA37E.BIN: src/CMakeFiles/../ANYKA37E.BIN.dir/build.make
src/../ANYKA37E.BIN: src/lv_qrcode/liblv_qrcode_lib.a
src/../ANYKA37E.BIN: src/lvgl/liblvgl_lib.a
src/../ANYKA37E.BIN: src/lv_drivers/liblv_drivers_lib.a
src/../ANYKA37E.BIN: src/api/libleo_api_lib.a
src/../ANYKA37E.BIN: src/iniparser/libiniparser.a
src/../ANYKA37E.BIN: src/tuya_batch_production_sdk/xls/libxls.a
src/../ANYKA37E.BIN: src/lib/anyka/libplat_tde.so
src/../ANYKA37E.BIN: src/lib/anyka/libplat_common.so
src/../ANYKA37E.BIN: src/lib/anyka/libplat_thread.so
src/../ANYKA37E.BIN: src/lib/anyka/libplat_mem.so
src/../ANYKA37E.BIN: src/lib/anyka/libplat_osal.so
src/../ANYKA37E.BIN: src/lib/anyka/libplat_log.so
src/../ANYKA37E.BIN: src/lib/anyka/libplat_dbg.so
src/../ANYKA37E.BIN: src/lib/anyka/libmpi_vdec.so
src/../ANYKA37E.BIN: src/lib/anyka/libakv_decode.so
src/../ANYKA37E.BIN: src/lib/anyka/libmpi_venc.so
src/../ANYKA37E.BIN: src/lib/anyka/libakv_encode.so
src/../ANYKA37E.BIN: src/lib/anyka/libplat_ao.so
src/../ANYKA37E.BIN: src/lib/anyka/libplat_vqe.so
src/../ANYKA37E.BIN: src/lib/anyka/libakaudiofilter.so
src/../ANYKA37E.BIN: src/lib/anyka/libplat_ai.so
src/../ANYKA37E.BIN: src/lib/anyka/../freetype/libfreetype.a
src/../ANYKA37E.BIN: src/lib/anyka/../mad/libmad.a
src/../ANYKA37E.BIN: src/lib/anyka/../jpg/libjpeg.a
src/../ANYKA37E.BIN: src/lib/anyka/../g711/libg711.a
src/../ANYKA37E.BIN: src/lib/anyka/../resample/libsamplerate.a
src/../ANYKA37E.BIN: src/iniparser/libiniparser.a
src/../ANYKA37E.BIN: src/lib/live555/libBasicUsageEnvironment.a
src/../ANYKA37E.BIN: src/lib/live555/libgroupsock.a
src/../ANYKA37E.BIN: src/lib/live555/libliveMedia.a
src/../ANYKA37E.BIN: src/lib/live555/libUsageEnvironment.a
src/../ANYKA37E.BIN: src/lib/anyka/../tuya/libtuya_ipc.a
src/../ANYKA37E.BIN: src/lib/anyka/../tuya/libmbedtls.a
src/../ANYKA37E.BIN: src/lib/anyka/../../api/libleo_api_lib.a
src/../ANYKA37E.BIN: src/lib/anyka/../iconv/libiconv.a
src/../ANYKA37E.BIN: src/tuya_batch_production_sdk/xls/libxls.a
src/../ANYKA37E.BIN: src/api/onvif/lib/libbase64.a
src/../ANYKA37E.BIN: src/api/onvif/lib/libmd5.a
src/../ANYKA37E.BIN: src/api/onvif/lib/libmxml.a
src/../ANYKA37E.BIN: src/api/onvif/lib/libonvif.a
src/../ANYKA37E.BIN: src/api/onvif/lib/libsha1.a
src/../ANYKA37E.BIN: src/CMakeFiles/../ANYKA37E.BIN.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --bold --progress-dir=/home/leo/workspace/ruian_2wire/common/app/common/CMakeFiles --progress-num=$(CMAKE_PROGRESS_42) "Linking CXX executable ../ANYKA37E.BIN"
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && $(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/../ANYKA37E.BIN.dir/link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
src/CMakeFiles/../ANYKA37E.BIN.dir/build: src/../ANYKA37E.BIN

.PHONY : src/CMakeFiles/../ANYKA37E.BIN.dir/build

src/CMakeFiles/../ANYKA37E.BIN.dir/clean:
	cd /home/leo/workspace/ruian_2wire/common/app/common/src && $(CMAKE_COMMAND) -P CMakeFiles/../ANYKA37E.BIN.dir/cmake_clean.cmake
.PHONY : src/CMakeFiles/../ANYKA37E.BIN.dir/clean

src/CMakeFiles/../ANYKA37E.BIN.dir/depend:
	cd /home/leo/workspace/ruian_2wire/common/app/common && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /home/leo/workspace/ruian_2wire/common/app/common /home/leo/workspace/ruian_2wire/common/app/common/src /home/leo/workspace/ruian_2wire/common/app/common /home/leo/workspace/ruian_2wire/common/app/common/src /home/leo/workspace/ruian_2wire/common/app/common/src/ANYKA37E.BIN.dir/DependInfo.cmake --color=$(COLOR)
.PHONY : src/CMakeFiles/../ANYKA37E.BIN.dir/depend

