#ifndef _LANGUAGE_H
#define _LANGUAGE_H



typedef enum{
    //layout home
	LAYOUT_HOME_LANG_MONITOR_ID,
    LAYOUT_HOME_LANG_INTERCOM_ID,
    LAYOUT_HOME_LANG_PLAYBACK_ID,
    LAYOUT_HOME_LANG_DORMANCY_ID,
    LAYOUT_HOME_LANG_ATHOME_ID,
    LAYOUT_HOME_LANG_LEAVEHOME_ID,
    LAYOUT_HOME_LANG_DOOR_ID,
    LAYOUT_HOME_LANG_CANCEL_ID,
    //layout intercom
    LAYOUT_INTERPHONE_LANG_DEVICEISBUSY_ID,
    //layout monitor
    LAYOUT_MONITOR_LANG_PHOTO_ID,
    LAYOUT_MONITOR_LANG_RECORD_ID,
    LAYOUT_MONITOR_LANG_TALK_ID,
    LAYOUT_MONITOR_LANG_GARAGE_ID,
    LAYOUT_MONITOR_LANG_EXIT_ID,
    //layout photo
    LAYOUT_PHOTO_LANG_DELETE_ID,
    //layout playback
    LAYOUT_PHOTO_LANG_DELETESELECTED_ID,
    LAYOUT_PHOTO_LANG_DELETEALL_ID,
    //layout product_introduction
    LAYOUT_PRODUCT_INTRODUCTION_LANG_PRODUCTS_ID,
    //layout ring
    LAYOUT_RING_LANG_SETRING_ID,
    LAYOUT_RING_LANG_CUSTOMRINGTONES_ID,
    LAYOUT_RING_LANG_LOCALRINGTONES_ID,
    LAYOUT_RING_LANG_SYSTEMRINGTONES_ID,
    //layout set language
    LAYOUT_SETLANGUAGE_LANG_LANGUAGE_ID,
    //layout set network
    LAYOUT_SETNETWORK_LANG_ADDNETWORK_ID,
    LAYOUT_SETNETWORK_LANG_WIFIINFO_ID,
    LAYOUT_SETNETWORK_LANG_IPADDRESS_ID,
    LAYOUT_SETNETWORK_LANG_SECURITY_ID,
    //layout setting common
    LAYOUT_SETCOMMON_LANG_NETWORKRESET_ID,
    //layout setting password
    LAYOUT_SETPASSWORD_LANG_PLEASEINPUTPASSWORD_ID,
    LAYOUT_SETPASSWORD_LANG_INCORRECTPASSWORD_ID,
    LAYOUT_SETPASSWORD_LANG_PASSWORDRESET_ID,
    LAYOUT_SETPASSWORD_LANG_NEWPASSWORD_ID,
    LAYOUT_SETPASSWORD_LANG_CONFIRMPASSWORD_ID,
    LAYOUT_SETPASSWORD_LANG_PASSWORDNOMATCH_ID,
    LAYOUT_SETPASSWORD_LANG_APPLY_ID,
    //layout setting room no
    LAYOUT_SETROOMNO_LANG_YOURCURRETROOM_ID,
    LAYOUT_SETROOMNO_LANG_ENTERSETNUMBER_ID,
    //layout setting 
    LAYOUT_SETTING_LANG_SETROOMID_ID,
    LAYOUT_SETTING_LANG_SETTIME_ID,
    LAYOUT_SETTING_LANG_SCREENSAVER_ID,
    LAYOUT_SETTING_LANG_OTHER_ID,
    LAYOUT_SETTING_LANG_RESET_ID,
    LAYOUT_SETTING_LANG_RING_ID,
    LAYOUT_SETTING_LANG_RINGTIME_ID,
    LAYOUT_SETTING_LANG_DOORBELL_ID,
    LAYOUT_SETTING_LANG_RINGTONE_ID,
    LAYOUT_SETTING_LANG_DEVICEID_ID,
    LAYOUT_SETTING_LANG_CONFIRM_ID,
    LAYOUT_SETTING_LANG_CANCEL_ID,
    LAYOUT_SETTING_LANG_FORMAT_ID,
    LAYOUT_SETTING_LANG_VIDEO_ID,
    LAYOUT_SETTING_LANG_OFF_ID,
    LAYOUT_SETTING_LANG_ON_ID,
    LAYOUT_SETTING_LANG_RECORD_ID,
    LAYOUT_SETTING_LANG_MOTIONDETECTION_ID,
    LAYOUT_SETTING_LANG_DOORUNLOCKDELAY_ID,
    LAYOUT_SETTING_LANG_GARAGEUNLOCKDELAY_ID,
    LAYOUT_SETTING_LANG_PLEASEWAIT_ID,
    LAYOUT_SETTING_LANG_OUTDOOROFFLINE_ID,
    LAYOUT_SETTING_LANG_UPGRADE_ID,
    LAYOUT_SETTING_LANG_LANGUAGE_ID,
    LAYOUT_SETTING_LANG_SYSTEM_ID,
    LAYOUT_SETTING_LANG_SECURITYPASSWORD_ID,
    LAYOUT_SETTING_LANG_LOOKINGFORUNITOUTDOOR_ID,
    LAYOUT_SETTING_LANG_UNITOUTDOORHASFOUND_ID,
    LAYOUT_SETTING_LANG_PAIRCOMPLETE_ID,
    LAYOUT_SETTING_LANG_FINDOUTDOORUNIT_ID,
    LAYOUT_SETTING_LANG_WALLPAPERSETTING_ID,
    //layout system
    LAYOUT_SYSTEM_LANG_SOFTVERSION_ID,
    LAYOUT_SYSTEM_LANG_RELEASEDATE_ID,
    LAYOUT_SYSTEM_LANG_SDSPACE_ID,
    LAYOUT_SYSTEM_LANG_UUID_ID,
    //layout video
    LAYOUT_VIDEO_LANG_DELETE_ID,
    //layout connect wifi
    LAYOUT_CONNECTWIFI_LANG_INPUTWIFIPASSWORD_ID,
    //layout background
    LAYOUT_BACKGROUND_LANG_SETTINGFAILED_ID,
    LAYOUT_BACKGROUND_LANG_SETTING_ID,
    LAYOUT_BACKGROUND_LANG_SETWALLPAPER_ID,
    LAYOUT_BACKGROUND_LANG_RESTOREWALLPAPER_ID,
    //layout customize ring
    LAYOUT_CUSTOMZERING_LANG_SETTINGFAILED_ID,
    //layout add wifi
    LAYOUT_ADDWIFI_LANG_CONNECTING_ID,
    LAYOUT_ADDWIFI_LANG_CONNECTSUCCESSFUL_ID,
    LAYOUT_ADDWIFI_LANG_CONNECTFAIL_ID,
    LAYOUT_ADDWIFI_LANG_WIFINAMEEMPTY_ID,
    LAYOUT_ADDWIFI_LANG_WIFIPASSWORDSHORT_ID,
    LAYOUT_ADDWIFI_LANG_NOTFIND_ID,
    LAYOUT_ADDWIFI_LANG_INPUTWIFINAME_ID,
    LAYOUT_ADDWIFI_LANG_INPUTWIFIPASSWORD_ID,
    LAYOUT_ADDWIFI_LANG_WIFINAME_ID,
    LAYOUT_ADDWIFI_LANG_WIFIPASSWORD_ID,
    //layout network common
    LAYOUT_NETWORKCOMMON_LANG_OUTDOORUPGRADEOVER_ID,
    //week
    WEEK_LANG_MONDAY_ID,
    WEEK_LANG_TUESDAY_ID,
    WEEK_LANG_WEDNESDAY_ID,
    WEEK_LANG_THURSDAY_ID,
    WEEK_LANG_FRIDAY_ID,
    WEEK_LANG_SATURDAY_ID,
    WEEK_LANG_SUNDAY_ID,
    //month
    MONTH_LANG_JANUARY_ID,
    MONTH_LANG_FEBRUARY_ID,
    MONTH_LANG_MARCH_ID,
    MONTH_LANG_APRIL_ID,
    MONTH_LANG_MAY_ID,
    MONTH_LANG_JUNE_ID,
    MONTH_LANG_JULY_ID,
    MONTH_LANG_AUGUST_ID,
    MONTH_LANG_SEPTEMBER_ID,
    MONTH_LANG_OCTOBER_ID,
    MONTH_LANG_NOVEMBER_ID,
    MONTH_LANG_DECEMBER_ID,
    //btn
    BTN_LANG_CANCLE_ID,
    BTN_LANG_CONFIRM_ID,
    //screen
    LAYOUT_SETTING_LANG_SCREENOFF_ID,
    LAYOUT_SETTING_LANG_CLOCKDISPLAY_ID,
    //format
    LAYOUT_SETTING_LANG_FORMATDEVICE_ID,
    LAYOUT_SETTING_LANG_FORMATSDCARD_ID,
    //cctv
    LAYOUT_CCTV_LANG_SWITCH_ID,
    LAYOUT_CCTV_LANG_INPUTCCTVNAME_ID,
    LAYOUT_CCTV_LANG_CCTVNAME_ID,
    LAYOUT_CCTV_LANG_CCTVNOONLINE_ID,
    LAYOUT_CCTV_LANG_ADDDEVICE_ID,
    LAYOUT_CCTV_LANG_DISCOVERDDEVICE_ID,
    LAYOUT_CCTV_LANG_CCTV_ID,
    LAYOUT_CCTV_LANG_IPADDRESS_ID,
    LAYOUT_CCTV_LANG_ACCOUNT_ID,
    LAYOUT_CCTV_LANG_PASSWORD_ID,
    LAYOUT_CCTV_LANG_ADDCCTV_ID,
    LAYOUT_CCTV_LANG_BRAND_ID,
    LAYOUT_CCTV_LANG_REGISTER_ID,
    LAYOUT_CCTV_LANG_SETBRAND_ID,
    
    LAYOUT_SUNNY_ID,
    LAYOUT_RAIN_ID,
    LAYOUT_SNOW_ID,
    LAYOUT_CLOUD_ID,

    LAYOUT_SCREEN_RESOLETION_ID,
    LAYOUT_SET_FLOOR_NUMBER_ID,
    LAYOUT_NOBODY_AT_HOME_ID,
	LANG_STR_ID_TOTAL,
}layout_lang_id;


char *str_get(layout_lang_id id);

char *mon_str_get(int mon);

char *week_str_get(int week);

const void*btns_str_get();

const char **btnmatrix16_str_get();

const char **btnmatrix7_str_get();

const char **brand_str_value_get(int value);
#endif  